spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tLU1TSzrSa89wkjZ91i
      secret-key: YC3aFd8QgZoz5xCYIgs5DaSwNdBvhd
      oss:
        endpoint: oss-cn-nanjing.aliyuncs.com
        bucket: mymall-yxz
      sms:
        host: "https://dfsns.market.alicloudapi.com"
        path: "/data/send_sms"
        appcode: "9cbb94f232034fa2a9a5edcb6fed26b7"
        templete: "TPL_0000"

  application:
    name: mymall-third-party
server:
  port: 30000
