spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: 
      secret-key: 
      oss:
        endpoint: oss-cn-nanjing.aliyuncs.com
        bucket: mymall-yxz

  application:
    name: mymall-third-party
server:
  port: 30000
